# Generated by Django 3.2.8 on 2021-10-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
