# Generated by Django 3.2.8 on 2006-01-01 03:16

from django.db import migrations, models
import django.db.models.deletion
import e_shop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_products', '0003_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=e_shop_products.models.upload_gallery_image_path, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_shop_products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
