# Generated by Django 3.2.8 on 2021-11-22 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_products', '0005_product_visit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=150, null=True, verbose_name='نویسنده کتاب'),
        ),
        migrations.AddField(
            model_name='product',
            name='book_genre',
            field=models.CharField(max_length=150, null=True, verbose_name='ژانر کتاب'),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn_book',
            field=models.BigIntegerField(null=True, verbose_name='شابک کتاب '),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='کد کتاب '),
        ),
        migrations.AddField(
            model_name='product',
            name='publication_date',
            field=models.CharField(max_length=150, null=True, verbose_name='تاریخ چاپ'),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.CharField(max_length=150, null=True, verbose_name='نوبت چاپ'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='translator',
            field=models.CharField(max_length=150, null=True, verbose_name='مترجم کتاب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان کتاب'),
        ),
    ]
