# Generated by Django 3.2.8 on 2021-11-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_products', '0006_auto_20211122_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True, verbose_name='عنوان در آدرس'),
        ),
    ]
