# Generated by Django 3.2.8 on 2021-11-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_products', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
