# Generated by Django 3.2.8 on 2020-11-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_products', '0009_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ghate_book',
            field=models.CharField(max_length=150, null=True, verbose_name='قطع'),
        ),
        migrations.AddField(
            model_name='product',
            name='jeld_book',
            field=models.CharField(max_length=150, null=True, verbose_name='جلد'),
        ),
    ]
