# Generated by Django 3.2.8 on 2021-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_products', '0010_auto_20201126_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn_book',
            field=models.CharField(max_length=150, null=True, verbose_name='شابک کتاب '),
        ),
    ]
