# Generated by Django 3.2.8 on 2021-11-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True, verbose_name='عنوان در آدرس'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=150, verbose_name=' عنوان دسته'),
        ),
    ]
