# Generated by Django 3.2.8 on 2006-01-01 02:30

from django.db import migrations, models
import e_shop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=e_shop_settings.models.upload_image_path, verbose_name='تصویر لوگو'),
        ),
    ]
