# Generated by Django 3.2.8 on 2021-11-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_settings', '0005_auto_20060101_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnsettings',
            name='image',
        ),
    ]
