# Generated by Django 3.2.8 on 2021-11-26 09:42

from django.db import migrations, models
import e_shop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_settings', '0007_delete_returnsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='سوال')),
                ('image', models.ImageField(blank=True, null=True, upload_to=e_shop_settings.models.upload_image_path, verbose_name='تصویر ')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'رویه بازگشت کالا ',
                'verbose_name_plural': 'رویه بازگشت کالا',
            },
        ),
    ]
