# Generated by Django 3.2.8 on 2020-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_settings', '0009_remove_returnsettings_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='سوال')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'سوالات متداول ',
                'verbose_name_plural': 'سوالات متداول ',
            },
        ),
    ]
