# Generated by Django 3.2.8 on 2020-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_settings', '0010_faqsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'قوانین و مقررات سایت',
                'verbose_name_plural': 'قوانین و مقررات سایت ',
            },
        ),
    ]
