# Generated by Django 3.2.8 on 2020-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_settings', '0011_lawsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس تلگرام'),
        ),
    ]
