# Generated by Django 3.2.8 on 2020-11-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_settings', '0012_auto_20201126_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='telegram',
            new_name='linkedin',
        ),
    ]
