# Generated by Django 3.2.8 on 2021-11-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پیگیری سبد پرداخت شده'),
        ),
    ]
