# Generated by Django 3.2.8 on 2020-11-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_order', '0002_order_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='کد پیگیری سبد پرداخت شده'),
        ),
    ]
