# Generated by Django 3.2.8 on 2005-12-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_order', '0004_auto_20060101_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, max_length=500, verbose_name='آدرس مشتري'),
        ),
        migrations.AlterField(
            model_name='order',
            name='family',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام خانوادگي مشتري'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره تماس مشتري'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام مشتري'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='كد پستي مشتري'),
        ),
    ]
