# Generated by Django 3.2.8 on 2005-12-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_order', '0005_auto_20060101_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='كد پستي مشتري'),
        ),
    ]
