# Generated by Django 3.2.8 on 2005-12-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_order', '0007_auto_20060101_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.TextField(blank=True, max_length=500, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='provance',
            field=models.TextField(blank=True, max_length=500, verbose_name='استان'),
        ),
    ]
