# Generated by Django 3.2.8 on 2005-12-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_order', '0008_auto_20060101_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=500, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provance',
            field=models.CharField(blank=True, max_length=500, verbose_name='استان'),
        ),
    ]
