# Generated by Django 3.2.8 on 2005-12-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_order', '0009_auto_20060101_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='family',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگي مشتري'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='شماره تماس مشتري'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام مشتري'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provance',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='استان'),
        ),
    ]
