# Generated by Django 3.2.8 on 2006-01-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_order', '0010_auto_20060101_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره تماس مشتري'),
        ),
    ]
