# Generated by Django 3.2.8 on 2020-11-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='family',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
